#!/bin/bash

ACCOUNT=dmitryantonyuk
IMAGE=telegram-action
TAG=1.0.0

docker build -t ${ACCOUNT}/${IMAGE} .
docker tag ${ACCOUNT}/${IMAGE}:latest ${ACCOUNT}/${IMAGE}:${TAG}
docker push ${ACCOUNT}/${IMAGE}:${TAG}
