name: Notify

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: dantonyuk/telegram-action@master
      with:
        token: ${{ secrets.TELEGRAM_TOKEN }}
        destination: ${{ secrets.TELEGRAM_TO }}
